### ISSUE TITLE
Problems with live video

### ISSUE THREAD

**Issue by flymzero** [HiroyukiTamura/flutter_hls_parser#11]
The format of some live video files cannot pass regular expressions。
such as:
```
#EXTM3U x-tvg-url="https://iptv...
#EXTINF:-1 tvg-id="Blac....
```
code:
```dart
// -1
var string = _parseStringAttr(
    source: line,
    pattern: REGEXP_MEDIA_DURATION,
);
```
You can try this link：https://iptv-org.github.io/iptv/index.category.m3u

**Comment by HiroyukiTamura** [comment]
the provided file has wrong format.
The EXTINF tag must have positive number because it specifies the duration of a media segment.

cf.
[4.3.2.1  EXTINF](https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming-23#section-4.3.2.1)
https://github.com/google/ExoPlayer/issues/4192
