### ISSUE TITLE
Add complete working example

### ISSUE THREAD

**Issue by sanidhyaagrawal** [HiroyukiTamura/flutter_hls_parser#5]
Lack of proper example makes it really difficult for first-time users, please add a basic working example.

**Comment by SinoMiles** [comment]
@HiroyukiTamura  same issue  i think you can provide a  m3u8 downloader package for flutter

**Comment by khanems** [comment]
same issue

**Comment by HiroyukiTamura** [comment]
@SinoMiles 
already there is; https://github.com/tanersener/ffmpeg-kit

**Comment by HiroyukiTamura** [comment]
I'm so sorry for late response.
I updated the example with #15 .
If you have any idea to ease understanding, please reopen issue or PR.
